Update comment about how graceful socket closing works
stripe/smokescreen pull request #120
Opened 2020-08-31 21:34 UTC by alexmv

This comment was originally written in e1ec5a5b3cf2 and was not
updated when the graceful shutdown code as overhauled in 804861da2e37.

----

I'm not actually confident in the rationale that I updated this to.  I'd love to hear more about the reason, if what I wrote is not accurate.

2020-09-03 21:39 UTC, cds2-stripe commented
Hi there! Your rationale is correct. We pass wrapped `net.Conn`s to `goproxy` for a couple of reasons, including retaining a reference so that we can forcefully call `Close()`. I think it may be worth clarifying that we pass these wrapped connections, which are maintained by `ConnTracker`, to `goproxy` and that this is what allows us to support graceful termination.

Thank you for contributing to Smokescreen!

2020-09-03 22:02 UTC, alexmv commented
Thanks for the context!  Updated the wording.

I'm a little curious what the goji <-> goproxy bad interaction that's alluded to is -- that's the part of the comment that feels opaque to me.

2020-09-30 00:08 UTC, alexmv commented
Ping on this?

2020-09-30 00:18 UTC, cds2-stripe requested changes
Sorry for the delay, I missed the last update.

2020-09-30 00:18 UTC, cds2-stripe commented on pkg/smokescreen/smokescreen.go
> +	// know exaclty how long to wait until the connection has become idle, and
exaclty -> exactly

2020-09-30 00:41 UTC, alexmv commented
Updated; thanks for that catch?

Did you have thoughts on this:
> I'm a little curious what the goji <-> goproxy bad interaction that's alluded to is -- that's the part of the comment that feels opaque to me.

2020-09-30 01:41 UTC, cds2-stripe commented
@alexmv I was able to dig up a comment from Carl, who is also the author of the goji libraries, explaining why the interaction doesn't work as expected: https://github.com/stripe/smokescreen/pull/5#issuecomment-272520503

Hope this helps!

2020-09-30 01:41 UTC, cds2-stripe approved these changes

2020-09-30 01:42 UTC, merged