feature/add prometheus metrics
stripe/smokescreen pull request #179
Opened 2022-09-30 13:43 UTC by jmcconnell26

Hi! 

We've been looking to use smokescreen in production, and want to expose prometheus metrics to integrate with our monitoring stack.
I've raised this PR to make the changes required to enable exposing the existing metrics collected via prometheus.
Please let me know if there are any changes you'd like me to make!

Thanks,
Josh

2022-09-30 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stripe/smokescreen?pullRequest=179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stripe/smokescreen?pullRequest=179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stripe/smokescreen?pullRequest=179) it.</sub>

2023-01-18 20:18 UTC, cds2-stripe commented
Hey @jmcconnell26 ! Apologies for the delay here.

Is this still something you're interested in pursuing? If so I can bring this up at our team meeting. We're actually looking at moving to Prometheus internally so this is very timely.

2023-01-19 09:27 UTC, jmcconnell26 commented
Hi @cds2-stripe, yes this is something we would definitely be keen to push forward with!

There are one or two changes we made to our fork which need to be synced with this branch, but I can hopefully get those made at some point this week or next.

Thanks!
Josh

2023-01-19 16:59 UTC, jmcconnell26 commented
Hi @cds2-stripe, I've merged the changes we had been using internally. If there's anything else you'd like me to change, please just let me know!

Thanks,
Josh

2023-04-24 15:32 UTC, alexmv commented
We'd love this feature!  Anything we can do to help it get reviewed and merged?

2023-05-17 18:33 UTC, cds2-stripe commented
I'm reviewing and testing this now, incredibly sorry for the delays. @jmcconnell26 would you be willing to fix up the merge conflicts?

2023-05-17 19:07 UTC, cds2-stripe requested changes
Overall this looks great. I don't have any material feedback on the code, thanks for your tests and having the Prometheus client match the style / format of the existing statsd client.

I will need to do some more testing internally. We have some very high RPS endpoints using `IncrWithTags` and I'm curious to see any perf implications with the new usage of `constructTagArray`.

If you could fixup the merge conflict I can work on testing this in our QA environment.

2023-05-18 07:32 UTC, jmcconnell26 commented
Hi @cds2-stripe, of course! I've just updated the code to resolve the merge conflicts now. Just let me know if there are any more changes you want me to make!

2023-05-18 14:50 UTC, cds2-stripe requested changes

2023-05-18 14:50 UTC, cds2-stripe commented on pkg/smokescreen/metrics/metrics.go
> -	StatsdClient() statsd.ClientInterface
We wrap smokescreen internal with some of our other observability tooling, and we need to retain access to the underlying statsd client to pass to other internal libraries.

What would you think about keeping this in the interface (in a perfect world it wouldn't be there, but this has been there for a while) and returning nil from the prometheus client?

2023-05-18 21:19 UTC, cds2-stripe approved these changes
@jmcconnell26 I've tested this internally without any issues. We really appreciate the PR!

2023-05-18 21:21 UTC, cds2-stripe commented
Looks like `go vet -v ./...` is failing: https://github.com/stripe/smokescreen/actions/runs/5011619656/jobs/8997700754?pr=179

2023-05-19 07:13 UTC, jmcconnell26 commented
@cds2-stripe - apologies, I've updated, and hopefully fixed the issue with go vet

2023-05-19 12:56 UTC, cds2-stripe approved these changes

2023-05-19 12:56 UTC, cds2-stripe commented
Thanks again @jmcconnell26. Feel free to followup with another PR if you're interested in adding yourself to the contributors list - I'd be happy to approve!

2023-05-19 12:56 UTC, merged

2023-05-19 15:53 UTC, jmcconnell26 commented
Fantastic, many thanks @cds2-stripe for the review!